[package]
name = "program"
version = "0.1.0"
authors = ["Vasilii Tarasov <megg0009@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stl_io = "0.6.0"
nalgebra = "*"
libc = "*"
